import { TextEdit, Button, VerticalBox , HorizontalBox, GridBox} from "std-widgets.slint";

export component re inherits Window {
    width: 100%;
    height: 100%;

    Rectangle {
        background:red;
    }
}

export component WordpressBody inherits Window {
    width: 100%;
    height: 80%;

    GridBox {
        spacing-vertical: 10px;

        // headings
        Row {
            Rectangle {
                width: 30%;
                Text {color: black; text: "Enter Email Contents Here"; }

            }
            Rectangle {
                width: 30%;
                Text {color: black; text: "Formatted JSON";}
            }
            Rectangle {
                width: 30%;
                Text {color: black; text: "Upload Image";}
            }
        }

        // content bodys
        Row {
            Rectangle { 
                width: 30%;

                email := TextEdit {
                    font-size: 14px;
                    width: parent.width;
                    height: parent.height;
                    
                }
            }

            Rectangle { 
                background: blue; 
                width: 30%;

                correctJson := TextEdit {
                    font-size: 14px;
                    width: parent.width;
                    height: parent.height;
                    
                }

            }

            Rectangle { 
                background: yellow;
                width: 30%;
            }
        }
    }
}

export component AppWindow inherits Window {
    width: 500px;
    height: 400px;
    background: #D8E2DC;
    
    // colors: #D8E2DC, #FFFFFF, #FFCAD4

    VerticalLayout {
        HorizontalLayout {
            alignment: space-around;
            padding: 10px;
            height: 10%;
            Text {
                text: "logo";
            }
        }

        HorizontalLayout {
            alignment: space-around;
            height: 80%;
            WordpressBody{}
        }

        HorizontalLayout {
            alignment: end;
            padding: 10px;
            height: 10%;

            // behavior needed to "gray out" if no email content
            Button {
                max-height: 100%;
                text: "Submit";
                enabled: true;
                primary: true;
            }
        }
    }
    
        
    
    // callback request-increase-value();
    // VerticalBox {
    //     Text {
    //         text: "Counter: \{root.counter}";
    //     }
    //     Button {
    //         text: "Increase value";
    //         clicked => {
    //             root.request-increase-value();
    //         }
    //     }
    // }
 }
 